# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ fix_ci ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pipx and Poetry
      run: |
        pip install pipx &&
        pipx ensurepath &&

        python --version &&

        pipx install poetry==1.8.4 &&
        poetry --version

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run pytest tests --junit-xml=tests-results.xml

    - name: Render test results
      if: success() || failure()
      uses: dorny/test-reporter@v1
      continue-on-error: true
      with:
        name: Test results
        path: '**/tests-results.xml'
        reporter: java-junit

