name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install pipx and Poetry
      run: |
        pip install pipx &&
        pipx ensurepath &&

        python --version &&

        pipx install poetry==1.8.4 &&
        poetry --version

    - name: Install dependencies
      run: |
        poetry install

    - name: Run tests
      run: |
        poetry run pytest tests --junit-xml=tests-results.xml

    - name: Render test results
      if: success() || failure()
      uses: dorny/test-reporter@v1
      continue-on-error: true
      with:
        name: Test results
        path: '**/tests-results.xml'
        reporter: java-junit

